######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 13 15:40:19 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += interface.h maindialog.h updateThread.h
SOURCES += main.cpp maindialog.cpp updateThread.cpp
